In [1]:
import pandas as pd

In [7]:
df = pd.read_csv(r"C:\Users\kroze\Downloads\ecommerce_analytics_project\data\Ecommerce_Sales_Data_2024_2025.csv")
df

,Order ID,Order Date,Customer Name,Region,City,Category,Sub-Category,Product Name,Quantity,Unit Price,Discount,Sales,Profit,Payment Mode
0,10001,2024-10-19,Kashvi Varty,South,Bangalore,Books,Non-Fiction,Non-Fiction Ipsum,2,36294,5,68958.6,10525.09,Debit Card
1,10002,2025-08-30,Advik Desai,North,Delhi,Groceries,Rice,Rice Nemo,1,42165,20,33732.0,6299.66,Debit Card
2,10003,2023-11-04,Rhea Kalla,East,Patna,Kitchen,Juicer,Juicer Odio,4,64876,20,207603.2,19850.27,Credit Card
3,10004,2025-05-23,Anika Sen,East,Kolkata,Groceries,Oil,Oil Doloribus,5,37320,15,158610.0,36311.02,UPI
4,10005,2025-01-19,Akarsh Kaul,West,Pune,Clothing,Kids Wear,Kids Wear Quo,1,50037,10,45033.3,9050.04,Debit Card
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,14996,2024-06-25,Nishith Kulkarni,East,Kolkata,Books,Fiction,Fiction Veritatis,3,60671,0,182013.0,11853.15,Debit Card
4996,14997,2024-12-22,Aaina Chander,North,Jaipur,Toys,Doll,Doll Nulla,5,70048,0,350240.0,31237.23,Credit Card
4997,14998,2025-04-15,Dhanush Gara,South,Bangalore,Beauty,Lipstick,Lipstick Eaque,1,42162,15,35837.7,7827.50,Debit Card
4998,14999,2024-07-08,Divyansh Malhotra,East,Kolkata,Electronics,Smartwatch,Smartwatch Adipisci,4,13568,10,48844.8,6603.86,Credit Card
4999,15000,2024-02-04,Aarush Walla,West,Goa,Clothing,Kids Wear,Kids Wear Repellat,1,76762,10,69085.8,5785.85,Net Banking

In [9]:
df.shape

(5000, 14)

In [11]:
df.columns

Index(['Order ID', 'Order Date', 'Customer Name', 'Region', 'City', 'Category',
       'Sub-Category', 'Product Name', 'Quantity', 'Unit Price', 'Discount',
       'Sales', 'Profit', 'Payment Mode'],
      dtype='object')

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       5000 non-null   int64
 1   Order Date     5000 non-null   object
 2   Customer Name  5000 non-null   object
 3   Region         5000 non-null   object
 4   City           5000 non-null   object
 5   Category       5000 non-null   object
 6   Sub-Category   5000 non-null   object
 7   Product Name   5000 non-null   object
 8   Quantity       5000 non-null   int64
 9   Unit Price     5000 non-null   int64
 10  Discount       5000 non-null   int64
 11  Sales          5000 non-null   float64
 12  Profit         5000 non-null   float64
 13  Payment Mode   5000 non-null   object
dtypes: float64(2), int64(4), object(8)
memory usage: 547.0+ KB

In [15]:
df.isnull().sum()

Order ID         0
Order Date       0
Customer Name    0
Region           0
City             0
Category         0
Sub-Category     0
Product Name     0
Quantity         0
Unit Price       0
Discount         0
Sales            0
Profit           0
Payment Mode     0
dtype: int64

In [17]:
df.duplicated().sum()

0

In [27]:
df.dtypes

Order ID           int64
Order Date        object
Customer Name     object
Region            object
City              object
Category          object
Sub-Category      object
Product Name      object
Quantity           int64
Unit Price         int64
Discount           int64
Sales            float64
Profit           float64
Payment Mode      object
dtype: object

In [29]:
df['Order Date'] = pd.to_datetime(df['Order Date'])

In [33]:
df['Unit Price'] = df['Unit Price'].astype(float)

In [35]:
df['Discount'] = df['Discount'].astype(float)

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       5000 non-null   int64
 1   Order Date     5000 non-null   datetime64[ns]
 2   Customer Name  5000 non-null   object
 3   Region         5000 non-null   object
 4   City           5000 non-null   object
 5   Category       5000 non-null   object
 6   Sub-Category   5000 non-null   object
 7   Product Name   5000 non-null   object
 8   Quantity       5000 non-null   int64
 9   Unit Price     5000 non-null   float64
 10  Discount       5000 non-null   float64
 11  Sales          5000 non-null   float64
 12  Profit         5000 non-null   float64
 13  Payment Mode   5000 non-null   object
dtypes: datetime64[ns](1), float64(4), int64(2), object(7)
memory usage: 547.0+ KB

In [48]:
df = df.rename(columns={'Order ID':'order_id','Order Date':'order_date','Customer Name':'customer_name','Region':'region','City':'city','Category':'category','Sub-Category':'sub_category','Product Name':'product_name','Quantity':'quantity','Unit Price':'unit_price','Discount':'discount','Sales':'sales','Profit':'profit','Payment Mode':'payment_mode'})

In [50]:
df.columns

Index(['order_id', 'order_date', 'customer_name', 'region', 'city', 'category',
       'sub_category', 'product_name', 'quantity', 'unit_price', 'discount',
       'sales', 'profit', 'payment_mode'],
      dtype='object')

In [67]:
df = df.assign(year = lambda x : x.order_date.dt.year,
               month = lambda x : x.order_date.dt.month,
               year_month = lambda x : x.order_date.dt.to_period('M'))

In [69]:
df

,order_id,order_date,customer_name,region,city,category,sub_category,product_name,quantity,unit_price,discount,sales,profit,payment_mode,year,month,year_month
0,10001,2024-10-19,Kashvi Varty,South,Bangalore,Books,Non-Fiction,Non-Fiction Ipsum,2,36294.0,5.0,68958.6,10525.09,Debit Card,2024,10,2024-10
1,10002,2025-08-30,Advik Desai,North,Delhi,Groceries,Rice,Rice Nemo,1,42165.0,20.0,33732.0,6299.66,Debit Card,2025,8,2025-08
2,10003,2023-11-04,Rhea Kalla,East,Patna,Kitchen,Juicer,Juicer Odio,4,64876.0,20.0,207603.2,19850.27,Credit Card,2023,11,2023-11
3,10004,2025-05-23,Anika Sen,East,Kolkata,Groceries,Oil,Oil Doloribus,5,37320.0,15.0,158610.0,36311.02,UPI,2025,5,2025-05
4,10005,2025-01-19,Akarsh Kaul,West,Pune,Clothing,Kids Wear,Kids Wear Quo,1,50037.0,10.0,45033.3,9050.04,Debit Card,2025,1,2025-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,14996,2024-06-25,Nishith Kulkarni,East,Kolkata,Books,Fiction,Fiction Veritatis,3,60671.0,0.0,182013.0,11853.15,Debit Card,2024,6,2024-06
4996,14997,2024-12-22,Aaina Chander,North,Jaipur,Toys,Doll,Doll Nulla,5,70048.0,0.0,350240.0,31237.23,Credit Card,2024,12,2024-12
4997,14998,2025-04-15,Dhanush Gara,South,Bangalore,Beauty,Lipstick,Lipstick Eaque,1,42162.0,15.0,35837.7,7827.50,Debit Card,2025,4,2025-04
4998,14999,2024-07-08,Divyansh Malhotra,East,Kolkata,Electronics,Smartwatch,Smartwatch Adipisci,4,13568.0,10.0,48844.8,6603.86,Credit Card,2024,7,2024-07
4999,15000,2024-02-04,Aarush Walla,West,Goa,Clothing,Kids Wear,Kids Wear Repellat,1,76762.0,10.0,69085.8,5785.85,Net Banking,2024,2,2024-02

In [71]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       5000 non-null   int64
 1   order_date     5000 non-null   datetime64[ns]
 2   customer_name  5000 non-null   object
 3   region         5000 non-null   object
 4   city           5000 non-null   object
 5   category       5000 non-null   object
 6   sub_category   5000 non-null   object
 7   product_name   5000 non-null   object
 8   quantity       5000 non-null   int64
 9   unit_price     5000 non-null   float64
 10  discount       5000 non-null   float64
 11  sales          5000 non-null   float64
 12  profit         5000 non-null   float64
 13  payment_mode   5000 non-null   object
 14  year           5000 non-null   int32
 15  month          5000 non-null   int32
 16  year_month     5000 non-null   period[M]
dtypes: datetime64[ns](1), float64(4), int32(2), int64(2), object(7), period[M](1)
memory usage: 625.1+ KB

In [73]:
df.to_csv("cleaned_ecommerce_data.csv", index= False)